### ISSUE TITLE
M1/x86 desynchronization

### ISSUE THREAD

**Issue by aleksa2808** [cscorley/bevy_ggrs_rapier_example#22] opened 2023-03-19 21:04 UTC
(documenting the conversations from bevy engine's discord)

I've noticed a desynchronization that happens when one player is on an M1 processor and another on an x86 one. Upon investigation I've found out that this is caused by the ball rotation calculation where at a certain frame the M1 instance gives out a different rotation value than the x86 one. The sequence of events for this is the following:
1. at each frame, after the physics simulation step, `bevy_rapier` [updates](https://github.com/cscorley/bevy_rapier/blob/more-deterministic-context/src/plugin/systems.rs#L587) `bevy`'s `Transform` structures with the updated values using its [`utils::iso_to_transform`](https://github.com/cscorley/bevy_rapier/blob/more-deterministic-context/src/utils/mod.rs#L8) function
2. the `utils::iso_to_transform` function uses the [`from_rotation_z`](https://github.com/bitshifter/glam-rs/blob/0.22.0/src/f32/sse2/quat.rs#L166) method from the `Quat` type which is exported through `bevy` from the `glam` crate
3. the `from_rotation_z` function uses `stdlib`'s `f32::sin_cos` function

I've observed that for certain numbers the `f32::sin_cos` function returns different results on M1 and x86 processors which is caused by the use of hardware specific math functions. Upon replacing this call by `libm`'s `sincosf` implementation, the desynchronization issue disappears.

Based on these tests my opinion is that, if feasible, the best option for fixing this issue would be to work on a `force-libm`/`enhanced-determinism` feature in the `glam` crate which would build a more solid foundation not just for this demo but for all networked-rollback/physics enabled games.

Edit: Created a proposal to enable usage of both `std` and `libm` implementations in the `glam` crate: https://github.com/bitshifter/glam-rs/discussions/388

**Comment by aleksa2808** [comment] 2023-04-11 18:57
The `glam` crate was updated so that the `libm` flag would take precedence. I tried using the patched crate and it seems to eliminate the problem I had with the M1/x86 desyncs!

So now, I think there are two solutions to this issue, one short term and one long term:
1. the long term one would be to wait for `glam` to release a new version with the patch included, then update the dependency version in `bevy` and possibly in `bevy_rapier` as well, and then update this project to use these new versions
2. the short term one would be to create a fork of `glam` at [this](https://github.com/bitshifter/glam-rs/commit/a881b741e521d199c8ccb79ba347285527eff41c) commit and lower the version back to 0.22 so that, when the `glam` crate gets patched in `bevy_ggrs_rapier_example`, the project's dependencies would also use the forked version. Also, I think this also requires adding a dummy dependency on `glam` in this project so that we can enable the `libm` feature which would then enable it globally. Of course all of this is a bit of a hack, but it is a fix implementable now as opposed to a few months down the line.

What do you think @cscorley ?

P.S. I'm still not sure what I think about the `libm` and `std` flags being mutually exclusive. I still think that being able to enable both APIs might have been a better change overall. Case in point: imagine a project like this working cross platform but not because it itself enabled the libm flag, but because some other minor dependency did. If that dependency was later updated to not use the libm flag (or if it was just removed from the dependency tree) this project would start desyncing but it would be IMO much harder to figure out why.

**Comment by cscorley** [comment] 2023-04-16 15:51
Incredible debugging work, good job.   I'm very excited about this!

I think crate patching is fine as a temporary fix as part of this demo.  Once things update for glam and bevy, we can unravel it as necessary.  I think having code comments in the Cargo.toml to outline this plan could be enough reminder for people to check or follow along.

As far as libm goes, I'm not fully sure about all the nuances here.  I trust you'd make the right choices.  My instinct just says to make sure I've enabled it, which I think in this project it would be?  I think documentation there will carry us forward pretty far.  We can also setup a direct (unused) dependency on glam that is the same version we are patching and enable the feature there.  I believe then the tricky part is making sure it's the same one as everything else?  Now there's a missing cargo feature:  enabling sub-dependency features...

edit: 

Actually, just tried it with a direct dependency and it "just works".  No patching required -- and we can pin to that specific commit.  I assume this is because bevy is already on glam 0.23 and the git repo is recognized by cargo as the same version

edit 2: No, I am wrong.  I still needed to patch -- I misread the Cargo.lock diff.

**Comment by cscorley** [comment] 2023-04-16 16:04
Added import idea to WIP PR #25 ([commit](https://github.com/cscorley/bevy_ggrs_rapier_example/pull/25/commits/14dd22fa80808923445cceceb53780b3c06afd93)).  I think this is almost ready to merge.  Definitely should document more around this

**Comment by cscorley** [comment] 2023-04-16 16:25
oh wow, I think this actually fixes some desyncs I was having with WASM vs Native. Nice!

**Comment by aleksa2808** [comment] 2023-04-16 20:25
> oh wow, I think this actually fixes some desyncs I was having with WASM vs Native. Nice!

Yeah it should fix those as well since the issue ended up being more general than M1/x86. I think that WASM and M1 behave the same in this demo, so in that case you would get desyncs on x86/WASM.

> Actually, just tried it with a direct dependency and it "just works". No patching required -- and we can pin to that specific commit. I assume this is because bevy is already on glam 0.23 and the git repo is recognized by cargo as the same version
>
> edit 2: No, I am wrong. I still needed to patch -- I misread the Cargo.lock diff.

That approach didn't work for me since I was using the main branch of this repo, which relied on bevy that was using the 0.22 version of glam (while the libm change is on 0.23+). That's why I suggested to use a "downgraded" forked repo of glam (by just replacing 0.23 with 0.22 in Cargo.toml and keeping all else the same). However if the 0.10 upgrade branch is ready for merging soon than that would be a much better path for sure!

**Comment by cscorley** [comment] 2023-04-22 16:48
Yes, I am looking to merge it today.  The last Bevy upgrade I did something subtly broke and I didn't notice, so trying to be more careful this time around :slightly_smiling_face:

If you have time to confirm the branch is working for this issue, or to code review it, I would be grateful!

**Comment by aleksa2808** [comment] 2023-04-25 09:27
> If you have time to confirm the branch is working for this issue, or to code review it, I would be grateful!

Unfortunately I won't be able to test this right now as I'm traveling and won't have my tech with me until the end of May. :/ But hey, maybe by that time the 'glam' update will propagate to bevy? 😄
As for the MR itself, when I get a chance I'll go over it in full, but the commit you mentioned seems fine if bevy started using glam 0.23 as well.

Also, I just saw that glam 0.24 released with the libm change included! Faster than I expected! When it gets on crates.io a MR to bevy and bevy_rapier will be possible.

**Comment by cscorley** [comment] 2023-04-25 16:44
All good.  I appreciate your help regardless!  I am finally excited about my main game again thanks to your work :smiley:

I will likely merge this PR on Sunday this week.  We can close this issue after you've confirmed it works since I'm not likely to get an M1/M2 myself anytime soon.  Thanks again!

**Comment by aleksa2808** [comment] 2023-06-11 20:59
Hey, sorry for the long wait, finally got around to testing this again. In the two 3-4min runs I tested I didn't have any desync issues! I know the current solution is not "perfect" but that won't be a problem to fix once Bevy and other dependencies update so I think we can finally close this issue! (I am quite happy :) )

**Closed as completed** 2023-06-11 21:00 UTC

**Comment by cscorley** [comment] 2023-06-13 00:55
Thank you!
